### ISSUE TITLE
Crash when loading new world

### ISSUE THREAD

**Issue by Furionstrom** [CrankySupertoon01/Rebirth-3#58]
With the Reborn 3 template when loading a world minecraft crashes due to a server tick loop:

Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 10
	at silly511.backups.BackupManager.restoreSaving(BackupManager.java:141)
	at silly511.backups.BackupManager.serverTick(BackupManager.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_150_BackupManager_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by CrankySupertoon01** [comment]
It looks like it might be a issue with your backups. Care trying to remove all your backups and then try again

**Comment by CrankySupertoon01** [comment]
Im going to close this assumbing its resolved, if this comes up again respond again and ill reopen
